language: ruby
script: "bundle exec rake test:units"
sudo: false
cache: bundler

rvm:
- 2.5
- 2.4
- 2.3
- 2.2

gemfile:
- gemfiles/Gemfile.rails50
- gemfiles/Gemfile.latest-release
- gemfiles/Gemfile.shopify

matrix:
  exclude:
    - rvm: 2.2
      gemfile: gemfiles/Gemfile.shopify
  include:
    - rvm: 2.5
      gemfile: gemfiles/Gemfile.rails-edge

before_install:
  - gem update bundler
