language: ruby
script: "bundle exec rake test:units"
sudo: false
cache: bundler

rvm:
- 2.4
- 2.3
- 2.2

gemfile:
- gemfiles/Gemfile.rails50
- gemfiles/Gemfile.rails51

matrix:
  include:
    - rvm: 2.3
      gemfile: gemfiles/Gemfile.shopify
    - rvm: 2.4
      gemfile: gemfiles/Gemfile.shopify

before_install:
  - gem update bundler
